### ISSUE TITLE
Agenda and Dynamodb

### ISSUE THREAD

**Issue by ajshukury** [rschmukler/agenda#297] opened 2016-03-08 16:18 UTC
How hard would it be to change MANGO to DYNAMODB? Since we are in AWS environment and would like to DYNAMODB.

**Comment by OmgImAlexis** [comment] 2017-05-14 05:36
@droppedoncaprica can this please be closed as a dupe of #18

**Closed** 2017-05-17 14:18 UTC

**Comment by simison** [comment] 2017-06-22 23:00
@dylanjha if you'd like to help, there's now this: https://github.com/agenda/agenda/pull/443

**Comment by dylanjha** [comment] 2017-06-23 02:46
@simison happy to contribute where I can, but I don't have any use for a dynamo db adapter (or any other db adapter for that matter), nor do I have any experience with dynamo db! (#443) Is there another way I can assist with something?
