### ISSUE TITLE
Warning. Memory Leak (Not Production Ready)

### ISSUE THREAD

**Issue by minipolis** [rschmukler/agenda#142] opened 2015-02-01 00:36 UTC
Agenda will eventually crash your application since the memory consumption grows for every cycle.

**Comment by jgallen23** [comment] 2015-02-01 18:47
I've been running in production for awhile now.  Is there a specific type of job that is causing the memory leak?

**Comment by droppedoncaprica** [comment] 2015-02-02 15:32
This is a duplicate of #129

**Closed by droppedoncaprica** 2015-02-02 15:32 UTC
