### ISSUE TITLE
can we use agenda  with mongoose JS ?

### ISSUE THREAD

**Issue by ppbntl19** [rschmukler/agenda#185] opened 2015-07-29 17:19 UTC

**Comment by simonbogarde** [comment] 2015-07-29 21:53
Have a look at #156

**Comment by ppbntl19** [comment] 2015-07-30 05:42
Thanks
Getting this error whiile trying to connect database.
```
var agenda = new Agenda();
      agenda.database("localhost:27017/agenda-test",'agendaJobs')
           .processEvery('1 seconds')
           .maxConcurrency(20)
           .defaultLockLifetime(10000);
````
```
/home/ubuntu/workspace/node_modules/agenda/lib/agenda.js:39
  if (!url.match(/^mongodb:\/\/.*/)) {
          ^
TypeError: Cannot read property 'match' of undefined
```

**Comment by OmgImAlexis** [comment] 2017-05-14 05:17
@droppedoncaprica close this as a dupe of #156

**Closed** 2017-05-17 14:31 UTC
