### ISSUE TITLE
Priority has no effect?

### ISSUE THREAD

**Issue by bgriggs1** [rschmukler/agenda#177] opened 2015-06-12 19:46 UTC
I can't seem to use priority to influence the queue, but I'm not sure if I'm understanding how priority works correctly.

We sometimes have a queue that will balloon to over 1,000 with a max concurrency of 200. This is deliberate and not a problem.

If every job in that queue is priority 0, and a new job is scheduled to run immediately with a priority 100, my assumption is that the 100 job would be next to run.  But jobs seem to run in order regardless of what priority is assigned.

Is my assumption correct there? If not, how can higher priority jobs be bumped to head of the queue and run next regardless of queue size?

**Comment by loris** [comment] 2016-01-11 18:30
Do you still have the issue? I will close it down for now.
I just checked and priority seems to work as intended:

Here is a small snippet which define a long running (1 sec) job that display its data.
I enqueue 10 jobs with a normal priority, then 2 seconds later enqueue a new job with an highest priority.
```
agenda.define('test', { concurrency: 2 }, (job, done) => {
  console.log(new Date(), job.attrs.data);
  setTimeout(done, 1000);
});

agenda.on('ready', () => {
  Array(10).fill().forEach(x => agenda.now('test', 'normal job'));
  setTimeout(() => {
    const job = agenda.create('test', 'high priority job');
    job.schedule('now');
    job.priority(10);
    job.save(err => console.log('Added high priority job to queue'));
  }, 2000);
});
```

here is the output:
```
Mon Jan 11 2016 19:19:09 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:09 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:10 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:10 GMT+0100 (CET) 'normal job'
Added high priority job to queue
Mon Jan 11 2016 19:19:11 GMT+0100 (CET) 'high priority job'
Mon Jan 11 2016 19:19:11 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:12 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:12 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:13 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:13 GMT+0100 (CET) 'normal job'
Mon Jan 11 2016 19:19:14 GMT+0100 (CET) 'normal job'
```

As you can see, the `high priority job` is ran as soon as it is added to the queue, regardless of the remaining normal jobs

**Closed by loris** 2016-01-11 18:30 UTC
