### ISSUE TITLE
Restarting the server doesn't update the time for next-scheduled to run. 

### ISSUE THREAD

**Issue by arpwal** [rschmukler/agenda#175] opened 2015-06-10 03:16 UTC
I believe, the next-scheduled to run should be updated for every time the server is updated. Do you think otherwise?

**Comment by badjano** [comment] 2015-06-19 14:56
bump, this is a great module, but it is really annoying having to clean mongodb files everytime I change the interval of my task

**Comment by elssar** [comment] 2015-07-03 09:04
duplicate of #131

**Closed** 2017-05-17 14:30 UTC
