### ISSUE TITLE
Jobs not processing on multiple servers in parallel

### ISSUE THREAD

**Issue by krishna-koushik** [rschmukler/agenda#256] opened 2016-01-05 22:00 UTC
Hi,

I really like what agenda does and we are planning to replace our current scheduler service with it and we did a small POC on this. In our POC we started agenda in clustered mode and more than 1 server/machine. So multiple agenda server processes in 2 servers. we followed the suggested pattern in the documentation when starting up agenda server in clustered mode.
when we started testing we found that 

```javascript
var options = {
        processEvery: '10 seconds',
        maxConcurrency: 8,
        defaultConcurrency: 1,
        defaultLockLifetime: 30000
    };
var agenda = new Agenda(options);
agenda.database('localhost:27017/agenda_test', 'agenda_jobs');

agenda.define('hello world', {lockLifetime: 30000}, function(job, done) {
                console.log('Hello World', 'Agenda.name', agenda._name);
                setTimeout(function () {
                    console.log('Done working...');
                    done();
                }, 25000);
    });
```

In another js file

```javascript
var agenda = new Agenda();
agenda.database('localhost:27017/agenda_test', 'agenda_jobs');
for(var i = 0; i<= 100; i++) {
agenda.now('hello world', {id: i});
}
```

Scenarios:
Case 1: an Agenda Server, clustered mode running on 8 processors (8 agenda workers)

Observed: Everything works expected and its great.

Case 2: more than one machine with Agenda Server in clustered mode running (8+ processes)

Observed: 
* Agenda Server on machine A locks all 100 jobs and machine B is in a waiting mode
* After 30,000 ms machine B starts to pick up some of the jobs which machine A did not finish and both machine A and machine B runs same jobs.

What am I missing here? i was under the impression that the agenda processes would processes 1 job or up to 16 jobs at a time from this configuration without conflict (all run in parallel without fighting over locks).

Update: I have updated the code part here for more information.

**Comment by krishna-koushik** [comment] 2016-01-08 17:01
Just checking in if someone else ran into this problem. Also to add additional information on the above problem here is the job object which ran as duplicates in 2 different servers.

In Machine 1
```javascript
{ agenda: 
   { _name: 'SchedulerServer55298',
     _processEvery: 10000,
     _defaultConcurrency: 1,
     _maxConcurrency: 8,
     _definitions: { hello world: [Object] },
     _runningJobs: [ [Circular] ],
     _jobQueue: [ [Object], [Object], [Object] ],
     _defaultLockLifetime: 30000,
     _events: 
      { 'success:hello world': [Object],
        'fail:hello world': [Object],
        ready: [Function] },
     _mdb: 
      { domain: null,
        _events: {},
        _maxListeners: 10,
        s: [Object],
        serverConfig: [Getter],
        bufferMaxEntries: [Getter],
        databaseName: [Getter],
        options: [Getter],
        native_parser: [Getter],
        slaveOk: [Getter],
        writeConcern: [Getter] },
     _collection: { s: [Object] },
     _processInterval: 
      { _idleTimeout: 10000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 1452271771148,
        _monotonicStartTime: 238328156,
        _onTimeout: [Function: wrapper],
        _repeat: true },
     _nextScanAt: Fri Jan 08 2016 11:49:41 GMT-0500 (EST) },
  attrs: 
   { _id: 568fe80f2d11440137358944,
     data: 
      { id: 12},
     name: 'hello world',
     type: 'normal',
     priority: 0,
     nextRunAt: undefined,
     lastModifiedBy: null,
     lockedAt: Fri Jan 08 2016 11:48:21 GMT-0500 (EST),
     lastRunAt: Fri Jan 08 2016 11:49:11 GMT-0500 (EST) } }
```

In Machine 2
```javascript
{ agenda: 
   { _name: 'SchedulerServer55313',
     _processEvery: 10000,
     _defaultConcurrency: 1,
     _maxConcurrency: 8,
     _definitions: { hello world: [Object] },
     _runningJobs: [ [Circular] ],
     _jobQueue: [ [Object], [Object], [Object] ],
     _defaultLockLifetime: 30000,
     _events: 
      { 'success:hello world': [Object],
        'fail:hello world': [Object],
        ready: [Function] },
     _mdb: 
      { domain: null,
        _events: {},
        _maxListeners: 10,
        s: [Object],
        serverConfig: [Getter],
        bufferMaxEntries: [Getter],
        databaseName: [Getter],
        options: [Getter],
        native_parser: [Getter],
        slaveOk: [Getter],
        writeConcern: [Getter] },
     _collection: { s: [Object] },
     _processInterval: 
      { _idleTimeout: 10000,
        _idlePrev: [Object],
        _idleNext: [Object],
        _idleStart: 1452271792919,
        _monotonicStartTime: 238349928,
        _onTimeout: [Function: wrapper],
        _repeat: true },
        _nextScanAt: Fri Jan 08 2016 11:50:02 GMT-0500 (EST) },
  attrs: 
   { _id: 568fe80f2d11440137358944,
     data: 
      { id: 12},
     name: 'hello world',
     type: 'normal',
     priority: 0,
     nextRunAt: undefined,
     lastModifiedBy: null,
     lockedAt: Fri Jan 08 2016 11:47:12 GMT-0500 (EST),
     lastRunAt: Fri Jan 08 2016 11:49:32 GMT-0500 (EST) } }
```

**Comment by jdiamond** [comment] 2016-01-09 03:43
Are the clocks on the two machines synchronized?

**Comment by krishna-koushik** [comment] 2016-01-09 14:30
Yes. For my POC I started my 2 processes on my laptop.

**Comment by jdiamond** [comment] 2016-01-10 05:01
I tried running your scripts (updated to work with master) and this is what I think is happening.

Every process interval, Agenda looks to see what jobs need to run within the next 10 seconds (what you set `processEvery` to). All of your jobs need to run immediately so Agenda locks as many unlocked jobs as it can. It's theoretically possible for machine B to lock some of those jobs while machine A is acquiring its locks, but their process intervals would have to tick very closely to each other (within milliseconds) so probably not very likely.

This style of locking seems overly aggressive to me. Machine A is preventing machine B from processing any jobs until its locks expire. Maybe Agenda should have an option to limit how many jobs can be locked per process interval? I think it could be tuned to something like `processEvery / averageJobDuration * concurrency`.

So since you set `defaultConcurrency` to 1, each instance of Agenda can only run one job at a time. Your jobs take 25 seconds to run, so only one of your jobs will complete before the lock lifetimes of all the other jobs expire. Machine B will see the expired locks and think they now have permission to lock and run those jobs. 

I believe that machine A assumes its locks are still valid and eventually processes all jobs it initially locked and enqueued. At least I can't see any code where Agenda checks to see if the lock on a job has expired or been acquired by somebody else between initially locking and enqueueing the job and actually running it.

What's worse is machine A is also noticing those locks are expired and re-locking and re-enqueuing the same jobs it previously locked and enqueued. I can reliably reproduce a single instance of Agenda running the same jobs using the options in @krishna-koushik's scripts over and over. It will never stop running and re-running many of these jobs that should only be run once.

At a bare minimum, Agenda should be able to detect without even querying the database that the lock on an enqueued job has expired and that it should *not* process the job since some other instance may have locked it by then.

I also think Agenda should have a limit for how many jobs a single instance can lock per process interval. With the default lock lifetime, it would take at least 10 minutes before other instances could start acquiring locks and running jobs and that's not even guaranteed because the original instance could always re-acquire the locks before the others get a chance to.

**Comment by krishna-koushik** [comment] 2016-01-11 15:39
very well worded on what i was thinking. Thank you @jdiamond

**Comment by jakeorr** [comment] 2016-01-11 18:24
I ran into the issue of jobs being requeued and run multiple time that you are describing @jdiamond.

> At a bare minimum, Agenda should be able to detect without even querying the database that the lock on an enqueued job has expired and that it should not process the job since some other instance may have locked it by then.

I agree, this would be a good minimum. I had an idea to do this manually in the job processors, but the locked time is updated before they see it so they don't know if the job could have been requeued. I am working with a long running job which exacerbates the problem. I'm thinking that Agenda, in its current state anyway, isn't the right answer for these long running jobs. My interim fix has been to use a very long lock lifetime to avoid jobs being requeued (which becomes an issue if the server crashes because those long running jobs remained locked for a long time).

**Comment by jdiamond** [comment] 2016-01-11 20:18
I have a commit in my repo that tries to fix this: https://github.com/jdiamond/agenda/commit/5dd30cf0291627b105c0e61789005783425f8a62

I made a test case that fails without my fix (3 jobs that are supposed to get run 1 time each actually get run 7 times) and succeeds with my fix, but I'm experiencing random failures in some other tests that  don't seem to be related (they randomly fail with or without my fix). I'm pretty convinced the tests are just naturally prone to this because of the way they share an Agenda instance, but I don't have a simple solution yet so it might take a bit before I'm confident enough to submit a PR.

**Comment by jdiamond** [comment] 2016-01-12 02:00
I submitted the PR if anybody wants to test it out. I'm going to test/deploy it in my app to see if it resolves the duplicate jobs we started experiencing. Will update in a few days.

**Comment by krishna-koushik** [comment] 2016-01-14 16:57
I ll test this code today with my POC and will update

**Comment by krishna-koushik** [comment] 2016-01-16 18:54
I tested my POC with  agenda version 0.7.5 and it looks like the duplicate issue has been fixed so the job no longer runs on 2 agenda servers. We still have the problem where 1 server locks all the jobs which are meant to run so no load balancing. Thank you for that @jdiamond

**Comment by krishna-koushik** [comment] 2016-01-16 19:06
I tested my POC against the latest agenda code (0.7.6) and the duplicate running issue which i mentioned above has been addressed / fixed. We still have this problem where 1 of the agenda processes locks all the available job and to truly fix this issue if there could be some sort of configuration option of how many jobs a server can lock that would help a lot. Thanks @jdiamond for helping me out :)

**Comment by jakeorr** [comment] 2016-02-18 02:49
@krishna-koushik @jdiamond I have a pr up that addresses the other part of this issue, the multi process locking. You're welcome to have a look and comment if you would like.

https://github.com/rschmukler/agenda/pull/286

**Comment by krishna-koushik** [comment] 2016-03-01 20:26
Thank you :)

**Closed** 2016-03-01 20:26 UTC
